changed yaml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -46,6 +46,11 @@ jobs:
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
 
+      - name: Verify AWS Access
+        run: |
+          aws sts get-caller-identity
+          aws s3 ls s3://mani-state-2026/ || echo "Bucket access failed"
+
       - name: Clean Terraform Cache
         run: rm -rf .terraform .terraform.lock.hcl
 
